- name: variables preference
  hosts: localhost
  #vars:
    #Person: from play
    #WISHES: vars from Play level

  vars_files:
  - varsfiles.yaml

  #vars_prompt:
    #- name: Person, WISHES
      #prompt: please enter prompt
      #private: false

  tasks: 
  - name: vars with preference
    # vars:
    # Person: from task
    # WISHES: vars from Task level

    ansible.builtin.debug:
      msg: "Hi {{Person}}, {{WISHES}}"