- name: datatypes
  hosts: localhost
  vars:
    Course: Devops with AWS #string

    Tools: # list
     - linux
     - shell
     - ansible

    Experience: # map or dictionary
      Devops: 3 # number
      AWS: 2
      Docker: 1

    RealProject: true # boolean  

  tasks:
  - name: datatypes 
    ansible.builtin.debug:
      msg: "Course: {{Course}}, Tools discussed: {{Tools}}, Experience is {{Experience}}, Real project is {{RealProject}}" 
