- name: default value
  hosts: localhost
  tasks: 
  - name: default variable
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible')}}"

- name: upper case characters
  hosts: localhost
  vars:
   greetings: "good Morning"
  tasks:
  - name: changing uppercase letters
    ansible.builtin.debug:
      msg: "Hello {{greetings | upper}}" 

- name: lower case characters
  hosts: localhost
  vars:
   greetings: "GOOD MORNING"
  tasks:
  - name: changing lowercase letters
    ansible.builtin.debug:
      msg: "Hello {{greetings | lower}}"  

- name: remove duplicates
  hosts: localhost
  vars: 
   numbers: [1,2,3,4,4,3,2,5,6]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "print list {{numbers | unique}}"

- name: min and max
  hosts: localhost
  vars:
    ages: [25,26,28,29] 
  tasks:     
  - name: print min and max
    ansible.builtin.debug:
      msg: "min age is: {{ages | min}} and max age is {{ages | max}}"


- name: convert dictionary to items/lists
  hosts: localhost
  vars:
   my_dict:
    Course: ansible
    Trainer: Sivakumar
    Duration: 120hrs
  tasks:
  - name: Before convert
    ansible.builtin.debug:
      msg: "Before convert {{my_dict}}"  
  
  - name: After Convert 
    ansible.builtin.debug:
      msg: "After convert {{my_dict | dict2items}}"

