- name: default value
  hosts: localhost
  tasks: 
  - name: default variable
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible')}}"

- name: upper case characters
  hosts: localhost
  vars:
   greetings: "good Morning"
  tasks:
  - name: changing uppercase letters
    ansible.builtin.debug:
      msg: "Hello {{greetings | upper}}" 

- name: lower case characters
  hosts: localhost
  vars:
   greetings: "GOOD MORNING"
  tasks:
  - name: changing lowercase letters
    ansible.builtin.debug:
      msg: "Hello {{greetings | lower}}"           