- name: default value
  hosts: localhost
  tasks: 
  - name: default variable
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible')}}"

- name: upper case characters
  hosts: localhost
  vars:
   greetings: "good Morning"
  tasks:
  - name: changing uppercase letters
    ansible.builtin.debug:
      msg: "Hello {{greetings | upper}}" 

- name: lower case characters
  hosts: localhost
  vars:
   greetings: "GOOD MORNING"
  tasks:
  - name: changing lowercase letters
    ansible.builtin.debug:
      msg: "Hello {{greetings | lower}}"  

- name: remove duplicates
  hosts: local host
  vars: 
  - numbers: [1,2,3,4,4,3,2,5,6]
  tasks:
    ansible.builtin.debug:
      msg: "print list {{numbers | unique}}"
