- name: install all packages
  hosts: localhost
  become: yes
  tasks:
  - name: installing packages
    ansible.builtin.dnf:
      name: "{{item}}"
      state: latest

    loop: 
    - mysql
    - nginx
    - postfix  