# install few packages and uninstall some packages
- name: install and uninstall packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packages 
    ansible.builtin.dnf:
      name: "{{name.item}}"
      state: "{{state.item}}"

    loop:
    - {name: mysql, state: latest}
    - {name: nginx, state: absent}
    - {name: postfix, state: absent}  
