#interview question is to install nginx and run nginx 
- name: install and run nginx 
  host: web
  become: yes #equal to -b root access 
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes 
