- name: variables
  hosts: localhost
  vars:
  course: "Devops"
  Trainer: "Siva kumar"
  Duration: "120 hrs"
  tasks:
  - name: working with variables
    ansible.builtin.debug:
      msg: "Hi we are learning {{ course }}, Trainer is {{ Trainer }} and Duration is {{ Duration }} "