- name: variables with prompt
  hosts: localhost
  vars_prompt:
    - name: USERNAME
      prompt: Please enter username
      private: false
    - name: PASSWORD
      prompt: Please enter password 
      private: true
  tasks: 
  - name: variables using prompt
    ansible.builtin.debug:
      msg: "username is: {{ USERNAME }}, password is: {{ PASSWORD }}"       